# Setup environment
import subprocess

Import("rootDirectory")
folder = "test"
execfile(rootDirectory + "Tools/SConscriptLib.py")

buildTest = True
if not iswin:
	# Test if cppunit is available
	if buildTest and subprocess.call("pkg-config cppunit", shell = True) == 0:
		curenv.ParseConfig("pkg-config --cflags --libs libavcodec libavformat libswscale libavutil libswresample libavfilter cppunit")
		curenv.Append(CCFLAGS = ["-fPIC", "-fvisibility=hidden", "-Wno-format-security", "-Wno-missing-braces", "-pthread"],
			LIBS = ["pthread"])
	else:
		buildTest = False
else:
	buildTest = False
	# No support for windows tests at the moment
	#curenv.Append(CPPPATH = ["..\\Dependencies\\include"],
	#	LIBPATH = ["..\\Dependencies\\lib", "..\\Dependencies\\bin"],
	#	LIBS = ["avcodec", "avformat", "swscale", "avutil", "swresample", "avfilter", "cppunit"],
	#	CCFLAGS = ["/MTd"])

if buildTest:
	curenv.Append(CPPPATH = [getAbsolutePath(p) for p in ["Include"]] + [getAbsolutePath("src")])

	# Add the plugin files directly because most of the functions are not exported
	test = curenv.Program("test", recursiveGlob(sourceFiles) +
		recursiveGlob(sourceFiles, "../src"))
	Export("test")
