# Define global variables
project = "TS3AudioBob"
versionFile = "src/Plugin.cpp"
#enableGettext = False
#enableClangLib = False
#winUse32 = False

# Setup environment
import os
rootDirectory = os.getcwd() + os.sep
execfile(rootDirectory + "Tools/SConstructLib.py")

# Execute subscripts
SConscript("src/SConscript", variant_dir = buildPrefix, duplicate = 0)

# Create Visual Studio solution
if doMSVS():
	SConscript("src/SConscript")

finish()
