# Setup environment
Import("rootDirectory")
folder = "src"
execfile(rootDirectory + "Tools/SConscriptLib.py")

if not iswin:
	curenv.ParseConfig("pkg-config --cflags --libs libavcodec libavformat libswscale libavutil libswresample libavfilter")
	curenv.Append(CCFLAGS = ["-fPIC", "-fvisibility=hidden", "-Wno-format-security", "-Wno-missing-braces"], LINKFLAGS = ["-lpthread"])
else:
	curenv.Append(CPPPATH = ["..\\Dependencies\\include"],
		LIBPATH = ["..\\Dependencies\\lib", "..\\Dependencies\\bin"],
		LIBS = ["avcodec", "avformat", "swscale", "avutil", "swresample", "avfilter"],
		CCFLAGS = ["/MTd"])
curenv.Append(CPPPATH = [getAbsolutePath(p) for p in ["Include"]])

createLibrary("libts3audiobob")
program = libts3audiobob
Export("program")
