# Setup environment
Import("rootDirectory")
folder = "src"
execfile(rootDirectory + "Tools/SConscriptLib.py")

if not iswin:
	curenv.Append(CCFLAGS = ["-fPIC", "-fvisibility=hidden", "-Wno-format-security", "-Wno-missing-braces"])
else:
	curenv.Append(LINKFLAGS = ["/subsystem:console"])
curenv.Append(CPPPATH = [getAbsolutePath(p) for p in ["Include"]])

createLibrary("libts3audiobob")
program = libts3audiobob
Export("program")
